version: '3.8'
services:
  frontend:
    image: taxapp-frontend
    build:
      context: ./frontend
    ports:
      - "8000:80"

  backend:
    image: taxapp-backend
    build: 
      context: ./backend

  mongo:
    image: mongo
    restart: always