version: '3.8'
services:
  frontend:
    image: nginx-dev
    build:
      context: ./frontend
    volumes:
      - ./frontend/index.html:/srv/http/example-app/index.html
      - ./frontend/styles:/srv/http/example-app/styles
      - ./frontend/scripts:/srv/http/example-app/scripts
    ports:
      - "8000:80"
    networks:
      - frontend
      - backend

  backend:
    image: node-api
    build: 
      context: ./backend
    networks:
      - backend

networks:
  frontend: {}
  backend: {}