version: '3.8'
services:
  frontend:
    image: nginx-dev
    build:
      context: ./frontend
    ports:
      - "8000:80"
    networks:
      - frontend
      - backend

  backend:
    image: node-api
    build: 
      context: ./backend
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  frontend: {}
  backend: {}